{% set name = "readuct" %}
{% set pkg_name = "scine-" + name %}
{% set version = "4.1.0" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/readuct/archive/refs/tags/{{ version }}.tar.gz
    sha256: 9cec0192a444403d6a8fd096509798c49fbd1eec298ec7194aba915e31f50782
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/4.0.0.tar.gz
    sha256: 54002c2082b6bb75672ec66bf9cf3935bbdf6b085ed9b4d7174cbdedb7c2275d
    folder: dev

build:
  number: 0
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - boost-cpp
    - eigen
    - gtest
    - gmock
    - libblas  # [linux]
    - scine-core
    - scine-utilsos
    - yaml-cpp
  run:
    - boost-cpp
    - yaml-cpp

test:
  commands:
    - test -f $PREFIX/bin/{{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    ReaDuct allows you to carry out structure optimizations, transition state searches
    and intrinsic reaction coordinate (IRC) calculations among other things
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/readuct

extra:
  recipe-maintainers:
    - awvwgk
